baseURL = "https://technorip.github.io/"
languageCode = "en-us"
paginate = 6
theme = "technorip"
title = "Technorip"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Service"
url = "#service"
weight = 3
[[menu.main]]
name = "Work"
url = "#portfolio"
weight = 4
[[menu.main]]
name = "Timeline"
url = "#resume"
weight = 5
[[menu.main]]
name = "Skills"
url = "#skills"
weight = 6
[[menu.main]]
name = "Blog"
url = "#blog"
weight = 7
[[menu.main]]
name = "Contact"
url = "#contact"
weight = 8

# Sitemap Menu
[[menu.sitemap]]
name = "About Us"
url = "about"
weight = 1
[[menu.sitemap]]
name = "Frequently Ask Question"
url = "#"
weight = 2
[[menu.sitemap]]
name = "Privacy & Policy"
url = "#"
weight = 3
[[menu.sitemap]]
name = "Latest Article"
url = "#"
weight = 4

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright Â© Portio 2020"
footerLogo = "images/contact/widget-logo.png"
# We're using formspree.io for form handling, paste your formspree url below
fabformURL  = "https://fabform.io/f/JpTXRUa"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"

[params.address]
address = "Makervillage, Kochi, India."
email = "info@technoripo.com"
openingHours = "Open from 10am to 6pm (execpt Stturday & Sundays)"
phone = "+(448) 833 5272 332"

[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "10.055828850762236"
longitude = "76.35411155782921"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/"
weight = 2
[[params.social]]
icon = "fa-pinterest-square"
url = "https://www.pinterest.com/"
weight = 3
[[params.social]]
icon = "fa-twitter-square"
url = "https://twitter.com/"
weight = 4
